### ISSUE TITLE
Polling thread can call pthread_join() on itself

### ISSUE THREAD

**Issue by jp-bennett** [pine64/libpinedio-usb#3]
Troubleshooting an issue that popped up in OpenWRT using musl led to this backtrace:

```Thread 4 (LWP 26 "meshtasticd"):
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
#1  0x00007f6cef80ecb5 in __syscall_cp_c (nr=202, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
#2  0x00007f6cef80e283 in __futex4_cp (addr=0x7f6cef407b70, op=128, val=2, to=<optimized out>) at src/thread/__timedwait.c:24
#3  __timedwait_cp (addr=addr@entry=0x7f6cef407b70, val=2, clk=clk@entry=0, at=at@entry=0x0, priv=128, priv@entry=1) at src/thread/__timedwait.c:52
#4  0x00007f6cef80fcfd in __pthread_timedjoin_np (t=0x7f6cef407b38, res=0x0, at=0x0) at src/thread/pthread_join.c:18
#5  0x000055eca5b71e45 in pinedio_deattach_interrupt (inst=0x7f6cef449068, int_pin=PINEDIO_PIN_D6) at .pio/libdeps/native/Pine libch341-spi Userspace library/libpinedio-usb.c:581
#6  0x000055eca5b08d2e in Ch341Hal::detachInterrupt (this=0x7f6cef449020, interruptNum=6) at src/platform/portduino/USBHal.h:96
#7  0x000055eca5b50c27 in SX126x::clearDio1Action (this=0x7f6cef408380) at .pio/libdeps/native/RadioLib/src/modules/SX126x/SX126x.cpp:484
#8  0x000055eca5a9f790 in SX126xInterface<SX1262>::disableInterrupt (this=0x7f6cef408060) at src/mesh/SX126xInterface.cpp:236
#9  0x000055eca5ac5637 in RadioLibInterface::isrLevel0Common (cause=RadioLibInterface::ISR_TX) at src/mesh/RadioLibInterface.cpp:58
#10 0x000055eca5ac5694 in RadioLibInterface::isrTxLevel0 () at src/mesh/RadioLibInterface.cpp:76
#11 0x000055eca5b71b9f in pinedio_pin_poll_thread (arg=0x7f6cef449068) at .pio/libdeps/native/Pine libch341-spi Userspace library/libpinedio-usb.c:528
#12 0x00007f6cef80f9d2 in start (p=0x7f6cef407ab8) at src/thread/pthread_create.c:207
#13 0x00007f6cef811314 in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC```

The notable thing here is that the polling thread is trying to call pthread_join() on its own thread. Apparently glibc lets us get away with this, though it's not clear that it should.

**Comment by jp-bennett** [comment]
My presumed fix is just a simple check whether the current thread is the same as the one being ended: https://github.com/jp-bennett/libch341-spi-userspace/commit/97b52241a04f2017fa417392921fe86461dbaff2
